services:
  - type: web
    name: smartutilitesaiapi
    runtime: node
    buildCommand: pip install yt-dlp && npm install && npx prisma generate && npx prisma db push --skip-generate
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
